-- Mello social database setup
-- Run this in Supabase SQL Editor after the existing profiles table setup.

alter table public.profiles
  add column if not exists is_private boolean not null default false,
  add column if not exists message_privacy text not null default 'everyone',
  add column if not exists notifications_enabled boolean not null default true,
  add column if not exists notes_enabled boolean not null default true,
  add column if not exists reels_enabled boolean not null default true,
  add column if not exists stickers_enabled boolean not null default true,
  add column if not exists profile_picture_url text;

create table if not exists public.follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

create table if not exists public.follow_requests (
  requester_id uuid not null references auth.users(id) on delete cascade,
  target_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (requester_id, target_id),
  check (requester_id <> target_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now(),
  check (sender_id <> recipient_id)
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 180),
  music_title text,
  music_artist text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours')
);

create table if not exists public.reels (
  id bigint generated by default as identity primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  video_path text not null,
  caption text check (caption is null or char_length(caption) <= 180),
  created_at timestamptz not null default now()
);

create table if not exists public.reel_likes (
  reel_id bigint not null references public.reels(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (reel_id, user_id)
);

create table if not exists public.reel_comments (
  id bigint generated by default as identity primary key,
  reel_id bigint not null references public.reels(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.follows enable row level security;
alter table public.follow_requests enable row level security;
alter table public.messages enable row level security;
alter table public.notes enable row level security;
alter table public.reels enable row level security;
alter table public.reel_likes enable row level security;
alter table public.reel_comments enable row level security;

-- Public profile discovery is okay; private content is enforced below.
drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated" on public.profiles for select to authenticated using (true);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check (id = auth.uid());

drop policy if exists "follows_read_authenticated" on public.follows;
create policy "follows_read_authenticated" on public.follows for select to authenticated using (true);
drop policy if exists "follows_insert_self" on public.follows;
create policy "follows_insert_self" on public.follows for insert to authenticated with check (follower_id = auth.uid());
drop policy if exists "follows_delete_self" on public.follows;
create policy "follows_delete_self" on public.follows for delete to authenticated using (follower_id = auth.uid());

drop policy if exists "requests_read_participant" on public.follow_requests;
create policy "requests_read_participant" on public.follow_requests for select to authenticated using (requester_id = auth.uid() or target_id = auth.uid());
drop policy if exists "requests_insert_self" on public.follow_requests;
create policy "requests_insert_self" on public.follow_requests for insert to authenticated with check (requester_id = auth.uid());
drop policy if exists "requests_delete_participant" on public.follow_requests;
create policy "requests_delete_participant" on public.follow_requests for delete to authenticated using (requester_id = auth.uid() or target_id = auth.uid());

drop policy if exists "messages_read_participant" on public.messages;
create policy "messages_read_participant" on public.messages for select to authenticated using (sender_id = auth.uid() or recipient_id = auth.uid());
drop policy if exists "messages_insert_sender" on public.messages;
create policy "messages_insert_sender" on public.messages for insert to authenticated with check (sender_id = auth.uid());
drop policy if exists "messages_delete_sender" on public.messages;
create policy "messages_delete_sender" on public.messages for delete to authenticated using (sender_id = auth.uid());

-- Notes are visible only to the author, followers, or everyone when the author's account is public.
drop policy if exists "notes_read_allowed" on public.notes;
create policy "notes_read_allowed" on public.notes for select to authenticated using (
  author_id = auth.uid()
  or exists (select 1 from public.profiles p where p.id = notes.author_id and not p.is_private)
  or exists (select 1 from public.follows f where f.follower_id = auth.uid() and f.following_id = notes.author_id)
);
drop policy if exists "notes_insert_self" on public.notes;
create policy "notes_insert_self" on public.notes for insert to authenticated with check (author_id = auth.uid());
drop policy if exists "notes_update_self" on public.notes;
create policy "notes_update_self" on public.notes for update to authenticated using (author_id = auth.uid()) with check (author_id = auth.uid());
drop policy if exists "notes_delete_self" on public.notes;
create policy "notes_delete_self" on public.notes for delete to authenticated using (author_id = auth.uid());

-- Reels are public for public profiles, or visible to approved followers for private profiles.
drop policy if exists "reels_read_allowed" on public.reels;
create policy "reels_read_allowed" on public.reels for select to authenticated using (
  author_id = auth.uid()
  or exists (select 1 from public.profiles p where p.id = reels.author_id and not p.is_private)
  or exists (select 1 from public.follows f where f.follower_id = auth.uid() and f.following_id = reels.author_id)
);
drop policy if exists "reels_insert_self" on public.reels;
create policy "reels_insert_self" on public.reels for insert to authenticated with check (author_id = auth.uid());
drop policy if exists "reels_update_self" on public.reels;
create policy "reels_update_self" on public.reels for update to authenticated using (author_id = auth.uid()) with check (author_id = auth.uid());
drop policy if exists "reels_delete_self" on public.reels;
create policy "reels_delete_self" on public.reels for delete to authenticated using (author_id = auth.uid());

drop policy if exists "reel_likes_read_authenticated" on public.reel_likes;
create policy "reel_likes_read_authenticated" on public.reel_likes for select to authenticated using (true);
drop policy if exists "reel_likes_insert_self" on public.reel_likes;
create policy "reel_likes_insert_self" on public.reel_likes for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "reel_likes_delete_self" on public.reel_likes;
create policy "reel_likes_delete_self" on public.reel_likes for delete to authenticated using (user_id = auth.uid());

drop policy if exists "reel_comments_read_authenticated" on public.reel_comments;
create policy "reel_comments_read_authenticated" on public.reel_comments for select to authenticated using (true);
drop policy if exists "reel_comments_insert_self" on public.reel_comments;
create policy "reel_comments_insert_self" on public.reel_comments for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "reel_comments_delete_self" on public.reel_comments;
create policy "reel_comments_delete_self" on public.reel_comments for delete to authenticated using (user_id = auth.uid());

create or replace function public.mello_profile_counts(target uuid)
returns table(followers bigint, following bigint)
language sql
security definer
set search_path = public
as $$
  select
    (select count(*) from public.follows where following_id = target),
    (select count(*) from public.follows where follower_id = target);
$$;

revoke all on function public.mello_profile_counts(uuid) from public;
grant execute on function public.mello_profile_counts(uuid) to authenticated;

-- Storage bucket for Mello Reels.
insert into storage.buckets (id, name, public) values ('mello-reels','mello-reels',false)
on conflict (id) do nothing;

drop policy if exists "mello_reels_upload_own" on storage.objects;
create policy "mello_reels_upload_own" on storage.objects for insert to authenticated
with check (bucket_id = 'mello-reels' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "mello_reels_update_own" on storage.objects;
create policy "mello_reels_update_own" on storage.objects for update to authenticated
using (bucket_id = 'mello-reels' and owner_id = auth.uid()::text);
drop policy if exists "mello_reels_delete_own" on storage.objects;
create policy "mello_reels_delete_own" on storage.objects for delete to authenticated
using (bucket_id = 'mello-reels' and owner_id = auth.uid()::text);
drop policy if exists "mello_reels_read_authenticated" on storage.objects;
create policy "mello_reels_read_authenticated" on storage.objects for select to authenticated
using (bucket_id = 'mello-reels');
